import "./globals.css";
import { inter, playfair, poppins } from "@/fonts/font";


export const metadata = {
  title: "Qurbaniya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${poppins.className} ${playfair.className} h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
